"""Procedural mesh writers (.obj) for 3dgrut playground parity.

The 3dgrut playground offers procedural primitives ('Quad') plus .obj assets
('Sphere', ...) that get inserted with a material type
(threedgrut_playground/engine.py add_primitive). VKGS consumes meshes from
files, so these helpers write equivalent geometry as Wavefront OBJ that
``Scene.add_mesh`` can reference.

OBJ contract (pinned against src/obj_loader.cpp / tinyobjloader):

- ``v``/``vn``/``vt`` + triangular ``f v/vt/vn`` faces are all the loader
  needs. No ``mtllib``/``usemtl`` is required: with no material library the
  loader appends a default grey material (baseColor 0.7, roughness 0.5,
  obj_loader.cpp:89-97) and clamps all face material ids to it
  (obj_loader.cpp:199-203). Override per instance via
  ``Scene.add_mesh(..., materials=[...])``.
- Normals are consumed when the face indices reference them
  (obj_loader.cpp:178-182); we always emit them so no averaging kicks in.
- Texture V is flipped on load (texCoord.y = 1 - vt.y, obj_loader.cpp:191).
"""

from __future__ import annotations

import math
import os
import tempfile

__all__ = [
    "write_quad_obj",
    "write_plane_obj",
    "write_sphere_obj",
    "ensure_procedural",
]

_HEADER = "# Generated by vkgs.geometry (vk_gaussian_splatting python layer)\n"


def write_quad_obj(path: str, size: float = 1.0) -> str:
    """Write a quad in the XZ plane, centered at the origin, normals +Y.

    ``size`` is the edge length. Two CCW triangles (front face up), UVs
    spanning [0, 1]^2. Equivalent of the 3dgrut playground 'Quad' procedural
    primitive. Returns the absolute path written.
    """
    s = float(size) / 2.0
    lines = [_HEADER, "o quad\n"]
    # x, z, u, v
    corners = [
        (-s, -s, 0.0, 0.0),
        (-s, s, 0.0, 1.0),
        (s, s, 1.0, 1.0),
        (s, -s, 1.0, 0.0),
    ]
    for x, z, _, _ in corners:
        lines.append(f"v {x:.9g} 0 {z:.9g}\n")
    for _, _, u, v in corners:
        lines.append(f"vt {u:.9g} {v:.9g}\n")
    lines.append("vn 0 1 0\n")
    # CCW when viewed from +Y (front face toward the normal)
    lines.append("f 1/1/1 2/2/1 3/3/1\n")
    lines.append("f 1/1/1 3/3/1 4/4/1\n")

    abspath = os.path.abspath(path)
    with open(abspath, "w", encoding="utf-8") as f:
        f.writelines(lines)
    return abspath


def write_plane_obj(path: str, size: float = 1.0) -> str:
    """Alias of :func:`write_quad_obj` (3dgrut calls it 'Quad', DCCs 'Plane')."""
    return write_quad_obj(path, size=size)


def write_sphere_obj(path: str, radius: float = 1.0, subdivisions: int = 32) -> str:
    """Write a closed UV sphere centered at the origin.

    ``subdivisions`` is the number of longitude sectors; latitude uses
    ``subdivisions // 2`` stacks (min 3). Vertex positions are shared
    (single seam-free manifold: V - E + F = 2); normals are the normalized
    positions; UVs are equirectangular per vertex, so the u seam wraps within
    the last sector column — fine for the factor-only materials these meshes
    are meant for, use a DCC-authored asset for seamless texturing.
    Equivalent of the 3dgrut playground 'Sphere' asset. Returns the absolute
    path written.
    """
    sectors = max(3, int(subdivisions))
    stacks = max(3, int(subdivisions) // 2)
    r = float(radius)

    lines = [_HEADER, "o sphere\n"]
    v_lines = []
    vt_lines = []
    vn_lines = []

    def emit(x, y, z, u, v):
        v_lines.append(f"v {x:.9g} {y:.9g} {z:.9g}\n")
        vt_lines.append(f"vt {u:.9g} {v:.9g}\n")
        n = math.sqrt(x * x + y * y + z * z)
        vn_lines.append(f"vn {x / n:.9g} {y / n:.9g} {z / n:.9g}\n")

    # 1: north pole; 2 + (i-1)*sectors + j: ring vertex; last: south pole
    emit(0.0, r, 0.0, 0.5, 1.0)
    for i in range(1, stacks):
        theta = math.pi * i / stacks
        y = r * math.cos(theta)
        rr = r * math.sin(theta)
        for j in range(sectors):
            phi = 2.0 * math.pi * j / sectors
            emit(rr * math.cos(phi), y, rr * math.sin(phi), j / sectors, 1.0 - i / stacks)
    emit(0.0, -r, 0.0, 0.5, 0.0)

    lines += v_lines + vt_lines + vn_lines

    def ring(i, j):  # 1-based OBJ index of ring i (1..stacks-1), sector j (wraps)
        return 2 + (i - 1) * sectors + (j % sectors)

    north = 1
    south = 2 + (stacks - 1) * sectors
    faces = []
    for j in range(sectors):
        faces.append((north, ring(1, j + 1), ring(1, j)))
    for i in range(1, stacks - 1):
        for j in range(sectors):
            a, b = ring(i, j), ring(i, j + 1)
            c, d = ring(i + 1, j + 1), ring(i + 1, j)
            faces.append((a, b, c))
            faces.append((a, c, d))
    for j in range(sectors):
        faces.append((south, ring(stacks - 1, j), ring(stacks - 1, j + 1)))

    for a, b, c in faces:
        lines.append(f"f {a}/{a}/{a} {b}/{b}/{b} {c}/{c}/{c}\n")

    abspath = os.path.abspath(path)
    with open(abspath, "w", encoding="utf-8") as f:
        f.writelines(lines)
    return abspath


_KINDS = {
    "quad": (write_quad_obj, {"size": 1.0}),
    "plane": (write_quad_obj, {"size": 1.0}),
    "sphere": (write_sphere_obj, {"radius": 1.0, "subdivisions": 32}),
}


def _fmt(value) -> str:
    return f"{value:g}".replace(".", "p").replace("-", "m")


def ensure_procedural(kind: str, cache_dir: str = None, **params) -> str:
    """Return the path of a cached procedural .obj, writing it on first use.

    ``kind`` is 'quad' | 'plane' | 'sphere' (case-insensitive, so 3dgrut
    geometry_type strings 'Quad'/'Sphere' work as-is). ``params`` are
    forwarded to the writer (size / radius / subdivisions) and become part of
    the cache key, so distinct parameter sets coexist. ``cache_dir`` defaults
    to <tempdir>/vkgs_procedural.
    """
    key = kind.strip().lower()
    if key not in _KINDS:
        raise ValueError(f"unknown procedural kind {kind!r}; expected one of {sorted(_KINDS)}")
    writer, defaults = _KINDS[key]
    merged = dict(defaults)
    for name, value in params.items():
        if name not in defaults:
            raise TypeError(f"{key} does not accept parameter {name!r}; expected {sorted(defaults)}")
        merged[name] = value

    if cache_dir is None:
        cache_dir = os.path.join(tempfile.gettempdir(), "vkgs_procedural")
    os.makedirs(cache_dir, exist_ok=True)

    stem = key + "".join(f"_{n}{_fmt(v)}" for n, v in sorted(merged.items()))
    path = os.path.join(cache_dir, stem + ".obj")
    if not os.path.isfile(path):
        writer(path, **merged)
    return os.path.abspath(path)
